apiVersion: apps/v1
kind: Deployment
metadata:
  name: cocktail-deployment  # Name for your deployment
spec:
  replicas: 2  # Number of pods (2 in this case)
  selector:
    matchLabels:
      app: cocktail-deploy  # Label to identify pods belonging to this deployment
  template:
    metadata:
      labels:
        app: cocktail-deploy  # Labels for the pods in the deployment
    spec:
      containers:
      - name: vue-cocktail  # Container name
        image: aspper/vue-cocktail:latest  # Your image reference
        # Add any container specific configurations here (e.g., ports, resources)
        ports:
        - containerPort: 80  # Port your application listens on

